app_name: my-app
docker:
  #
  # network_id | network_subnet | network_gatewas (required)
  # network configuration for the bridge networks used by the system agent
  #
  network_id: isha-net
  network_subnet: 172.100.100.0/24
  network_gateway: 172.100.100.1

mqtt:
  broker: tcp://127.0.0.1:1883
  username: my-username
  password: my-password
  enable_heartbeat: true
  heartbeat_interval: 20
